#!/bin/bash
source ~/bashrc/bashrc
if [ "$hostname" == "vl-mhale-gbc" ] || [ "$hostname" == "mhale-mac" ]; then
	debug "On trusted host"
        if [ -f $HOME/bashrc/gpg-functions.sh ] ; then
          source $HOME/bashrc/gpg-functions.sh
          gpg_activate
        fi
fi
~/bin/usr/bin/pass "${1+$@}"
