#!/bin/bash
if [[ $hostname == vl-mhale-gbc ]] || [[ $hostname == mhale-mac ]]; then
        if [ -f $HOME/bashrc/gpg-functions.sh ] ; then
          source $HOME/bashrc/gpg-functions.sh
          gpg_activate
        fi
fi
/usr/bin/pass "${1+$@}"
